### ISSUE TITLE
open_id 来源？

### ISSUE THREAD

**Issue by youzipi** [easyjack/FanKe-Ticket#1]
可以提供 open_id 库 吗？
或者去哪儿找的二维码？

**Comment by easyjack** [comment]
/滑稽
他们不是可以生成海报吗。你识别一下那个海报二维码，每个人生成的海报里面都有他自己的openid

**Comment by youzipi** [comment]
这都是链接分享的。。。

**Comment by easyjack** [comment]
那就，，有可能失效了？最近没在玩这个东西哈哈
